# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib shapegrid
#' @importFrom Rcpp sourceCpp
ellipse_gridcpp <- function(n, R, C) {
    .Call('_shapegrid_ellipse_gridcpp', PACKAGE = 'shapegrid', n, R, C)
}

#' @useDynLib shapegrid
#' @importFrom Rcpp sourceCpp
polygon_gridcpp <- function(n, nv, V) {
    .Call('_shapegrid_polygon_gridcpp', PACKAGE = 'shapegrid', n, nv, V)
}

#' @useDynLib shapegrid
#' @importFrom Rcpp sourceCpp
triangle_gridcpp <- function(n, V) {
    .Call('_shapegrid_triangle_gridcpp', PACKAGE = 'shapegrid', n, V)
}

