# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib shapegrid
#' @importFrom Rcpp sourceCpp
ellipse_gridcpp <- function(n, R, C) {
    .Call('_shapegrid_ellipse_gridcpp', PACKAGE = 'shapegrid', n, R, C)
}

